package filter

type FilterPolicy interface {
	// Name returns the name of the filter policy.
	Name() string

	// NewGenerator creates a new filter generator for this policy.
	NewGenerator() FilterGenerator

	// MayContain checks if the filter may contain the given key.
	//
	// The filter is generated by the FilterGenerator.
	MayContain(filter, key []byte) bool
}

type FilterGenerator interface {
	// Add adds a key to the filter generator.
	Add(key []byte)

	// Generate generates the filter data.
	Generate(b Buffer)
}

type Buffer interface {
	// Write appends data to the buffer.
	Write(p []byte) (n int, err error)
	// WriterByte appends a single byte to the buffer.
	WriteByte(ch byte) error
}
